version: "3.3"
services:
 bind:
    restart: always
    image: sameersbn/bind:9.16.1-20200524
    hostname: localhost
    ports:
      - "5003:53/tcp"
      - "5003:53/udp"
      - "10000:10000/tcp"
    volumes:
      - ./data/bind:/data
    environment:
      ROOT_PASSWORD: secretpassword